#####################################################
# Created 2020-05-20 --jha
####################################################
# SRC File name
SRCFILE = navier_stokes

HEADERS = ns_data.h ns_system.h

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -g
FFLAGS = -g

WITH_SUITESPARSE=1

sinclude ../../examples/examples.mk
