#####################################################
# Last Modified 2019-06-10 --jha
####################################################
# SRC File name

SRCFILE = amr_grids

#SRCFILE = triangulation2d
#WITH_CGAL=1

HEADERS = connected_components.h solve_estimate_mark.h

INCLUDE =

LIBS = 

# Switch between debug or optimized
CFLAGS = -g

## If external libraries support is compiled in the hazmath library,
## comment/uncomment what is necessary below.
WITH_LAPACK=1
WITH_HAZNICS=1
WITH_SUITESPARSE=1

sinclude ../examples.mk
