#####################################################
# Last Modified 2019-06-10 --jha
####################################################

# SRC File name
SRCFILE = heat_equation

HEADERS = $(SRCFILE)_data.h

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -g
FFLAGS = -g

## If external libraries support is compiled in the hazmath library,
## uncomment  the corresponding line below:
WITH_SUITESPARSE=1
WITH_LAPACK=0

sinclude ../examples.mk
