#####################################################
# Last Modified 2019-06-10 --jha 
####################################################

# SRC File name
SRCFILE = heat_equation

HEADERS = 

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -g
FFLAGS = -g

WITH_SUITESPARSE=1

sinclude ../examples.mk
