#ifndef BOOL_EG_MECHANICS
#define BOOL_EG_MECHANICS true
#endif

#ifndef BOOL_EG_PRESSURE
#define BOOL_EG_PRESSURE true
#endif

#ifndef BOOL_WEAKLY_IMPOSED_BC 
#define BOOL_WEAKLY_IMPOSED_BC true
#endif

#ifndef THETA_SIPG
#define THETA_SIPG 0
#endif

#ifndef THETA_SIPG_PRESSURE
#define THETA_SIPG_PRESSURE 1
#endif

#ifndef LAME_LAMBDA_GLOBAL
#define LAME_LAMBDA_GLOBAL 1e+06
#endif

#ifndef PENALTY_PARAMETER_RHO
#define PENALTY_PARAMETER_RHO 0.
#endif

#ifndef PENALTY_PARAMETER_GLOBAL
#define PENALTY_PARAMETER_GLOBAL 10e+00
#endif

#ifndef BC_PENALTY_PARAMETER_GLOBAL
#define BC_PENALTY_PARAMETER_GLOBAL 10e+00
#endif

#ifndef PENALTY_PARAMETER_PRESSURE_GLOBAL
#define PENALTY_PARAMETER_PRESSURE_GLOBAL 10e+00
#endif

#ifndef BC_PENALTY_PARAMETER_PRESSURE_GLOBAL
#define BC_PENALTY_PARAMETER_PRESSURE_GLOBAL 10e+00
#endif

#ifndef TOTAL_NUM_CYCLES_GLOBAL
#define TOTAL_NUM_CYCLES_GLOBAL 6
#endif

// the LAME_MU_GLOBAL is not used in the code yet...
#ifndef LAME_MU_GLOBAL
#define LAME_MU_GLOBAL 1e+00
#endif

