#####################################################
# Modified 2017-04-03 --jha & xh
# Last Modified 2018-08-30 --ltz1
####################################################
# SRC File name
SRCFILE = eg_biot

HEADERS = eg_biot_system.h \
	eg_biot_error.h \
	eg_biot_params.h

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -g
FFLAGS = -g

WITH_SUITESPARSE=1
WITH_LAPACK=1

sinclude ../examples.mk
