#####################################################
# Last Modified 2019-06-10 --jha
####################################################

SRCFILE = main_solver_xd_1d
#SRCFILE = main_meshing_xd_1d
HEADERS = supporting_xd_1d.h solver_xd_1d.h definitions_xd_1d.h

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -g -Wall


## If an external libraries support is compiled in the hazmath library,
## uncomment  the corresponding lines below:
WITH_SUITESPARSE=1
WITH_LAPACK=1

MAKE_LIB=0
sinclude ../examples.mk
