#####################################################
# Modified 2017-04-03 --jha & xh
# Last Modified 2018-08-30 --ltz1
####################################################
# SRC File name
SRCFILE = Maxwell

HEADERS = Maxwell_data.h 

HEADERS = 

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -g
FFLAGS = -g

WITH_SUITESPARSE=1

sinclude ../../examples/examples.mk
