#####################################################
# Modified 2017-04-03 --jha & xh
# Last Modified 2018-08-30 --ltz1
####################################################
# SRC File name
SRCFILE = symmgrad

HEADERS = problem_data.h variational_system.h

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -g
FFLAGS = -g

## If external libraries support is compiled in the hazmath library,
## uncomment  the corresponding line below:
WITH_SUITESPARSE=1
WITH_LAPACK=1
WITH_CGAL=0

sinclude ../examples.mk
