#####################################################
# Last Modified 2019-06-13 --ltz1
####################################################
# SRC File name
SRCFILE = darcy

HEADERS = darcy_system.h darcy_data.h

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -g
FFLAGS = -g

WITH_SUITESPARSE=1
WITH_LAPACK=1

sinclude ../examples.mk
