#####################################################
# Last Modified 2019-06-13 --ltz1
####################################################
# SRC File name
SRCFILE = darcy

HEADERS = darcy_system.h darcy_data.h

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -g
FFLAGS = -g

## If external libraries support is compiled in the hazmath library,
## uncomment  the corresponding line below:
WITH_SUITESPARSE=1
WITH_LAPACK=1
WITH_CGAL=1


sinclude ../examples.mk
