#####################################################
# Last Modified 2017-03-09 --ltz
####################################################

# SRC File name
SRCFILE = DarcyFlow

HEADERS_ADD = DarcySystem.h DarcyData.h

sinclude ../examples.mk

# Generate an error message if the HAZmath library is not built
$(HAZLIB):
	$(error The HAZmath library is not built or is not up to date)




