#####################################################
# Last Modified 2017-03-09 --ltz
####################################################

# SRC File name
SRCFILE = DarcyFlow

HEADERS_ADD = DarcySystem.h DarcyData.h

sinclude ../examples.mk



