#####################################################
# Last Modified 2017-03-08 --ltz
####################################################
# SRC File name
SRCFILE = HeatEquation

HEADERS = 

INCLUDE =

# if you have compiled hazmath with suitesparse support, uncomment the
# two lines below.
#SSDIR = /usr/local
#LIBS = -L$(SSDIR)/lib -lsuitesparseconfig -lcholmod -lamd -lcolamd -lccolamd -lcamd -lspqr -lumfpack -lamd -lcxsparse 

#INCLUDE = -I$(SSDIR)/include

sinclude ../examples.mk


