#####################################################
# Last Modified 2017-03-08 --ltz
####################################################
# SRC File name
SRCFILE = HeatEqn

sinclude ../examples.mk


