#####################################################
# Last Modified 2017-03-06 --ltz
####################################################
# SRC File name
SRCFILE = elliptic_p1

HEADERS = supporting_$(SRCFILE).h

INCLUDE =

LIBS = 

# Switch between debug or optimized
CFLAGS = -g 

## If external libraries support is compiled in the hazmath library,
## comment/uncomment what is necessary below. If libhazmath was
## configured with "lapack=yes" for example then we need "WITH_LAPACK=1" below. 
WITH_LAPACK=1
WITH_SUITESPARSE=1

sinclude ../examples.mk

