#####################################################
# Last Modified 2019-06-10 --jha
####################################################

# SRC File name
SRCFILE = amr

HEADERS = solve_estimate_mark.h

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -O

WITH_SUITESPARSE=0

sinclude ../examples.mk
