#####################################################
# Last Modified 2021-04-18 --ltz
####################################################
# SRC File name
#####################################################
# Last Modified 2019-06-10 --jha
####################################################
# SRC File name
SRCFILE = coarse_grid

HEADERS = 

INCLUDE =

LIBS = 

# Switch between debug or optimized
CFLAGS = -g

## If external libraries support is compiled in the hazmath library,
## comment/uncomment what is necessary below.
WITH_LAPACK=1
WITH_SUITESPARSE=1
#WITH_CGAL=1

sinclude ../../examples/examples.mk
