#####################################################
# Last Modified 2017-03-06 --ltz
####################################################

# SRC File name
SRCFILE = l

HEADERS = meshes_inline.h stereo_g.h

INCLUDE =

LIBS = 

# Switch between debug or optimized
CFLAGS = -g 

## If external libraries support is compiled in the hazmath library,
## comment/uncomment what is necessary below.
WITH_LAPACK=1
WITH_SUITESPARSE=1
#WITH_CGAL=1

sinclude ../../examples/examples.mk

