#####################################################
# Last Modified 2019-06-10 --jha
####################################################

# SRC File name
SRCFILE = grid_generate

HEADERS = 

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -g -Wall
FFLAGS = -g -Wall

WITH_SUITESPARSE=0

sinclude ../examples.mk
