#####################################################
# Modified 2017-04-03 --jha & xh
# Last Modified 2018-08-30 --ltz1
####################################################
# SRC File name
SRCFILE = stokes

HEADERS = stokes_data.h stokes_system.h

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -O
FFLAGS = -O

## If external libraries support is compiled in the hazmath library,
## uncomment  the corresponding line below:
WITH_SUITESPARSE=1
WITH_LAPACK=0

sinclude ../examples.mk
