#####################################################
# Last Modified 2021-07-21 --ltz
####################################################

testing = aaa

### SRC File name
SRCFILE = test_$(testing)

HEADERS = ra_examples.h

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -O

## If external libraries support is compiled in the hazmath library,
## comment/uncomment what is necessary below.
WITH_LAPACK=1
WITH_SUITESPARSE=1

sinclude ../examples.mk
