#####################################################
# Last Modified 2021-07-21 --ltz
####################################################
testing = brasil
### SRC File name
SRCFILE = test_$(testing)
#SRCFILE = test_brasil

HEADERS = ra_examples.h

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -O

## If external libraries support is compiled in the hazmath library,
## comment/uncomment what is necessary below.
WITH_LAPACK=1
WITH_SUITESPARSE=1

sinclude ../examples.mk
