#####################################################
# Last Modified 2020-10-25 --ltz
####################################################

# SRC File name
SRCFILE = aaa

HEADERS = aaa_example.h

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -O3

WITH_LAPACK=1

sinclude ../examples.mk
