#####################################################
# Last Modified 2019-06-10 --jha
####################################################

# SRC File name
SRCFILE = amr

HEADERS = solve_estimate_mark.h

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -g
FFLAGS = -g

WITH_SUITESPARSE=1

sinclude ../examples.mk
