#####################################################
# Modified 2017-04-03 --jha & xh
# Last Modified 2018-08-30 --ltz1
####################################################
# SRC File name
SRCFILE = solvers
#SRCFILE = test_Schwarz
#SRCFILE = solvers_frac
#SRCFILE = solvers_bsr

HEADERS =

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -O # -Wall
FFLAGS = -O # -Wall

## If external libraries support is compiled in the hazmath library,
## uncomment  the corresponding line below:
WITH_SUITESPARSE=1
WITH_LAPACK=1

sinclude ../examples.mk
