extern void squtri_(INT *nop);
extern void xyloc_(REAL *xy,INT *jsqu,INT *nx,INT *ny,INT *i,INT *j,REAL *hx,REAL *hy,REAL *xmin,REAL *ymin);
extern void bndry2_(INT *ib,INT *nx,INT *ny,INT *mini,INT *minj,INT *maxi,INT *maxj,INT *inumb);
extern void bess2_(INT *ib,INT *nx,INT *ny,INT *inumb,INT *ibess,INT *jbess);
extern void getm2_(INT *nx,INT *ny,INT *nvert,INT *nel,REAL *xcoord,REAL *ycoord,INT *je,INT *iflags,INT *ib,INT *inumb);
extern void cubtet_(INT *nop);
extern void xyzloc_(REAL *xyz,INT *jcub,INT *nx,INT *ny,INT *nz,INT *i,INT *j,INT *k,REAL *hx,REAL *hy,REAL *hz,REAL *xmin,REAL *ymin,REAL *zmin);
extern void bndry3_(INT *ib,INT *nx,INT *ny,INT *nz,INT *mini,INT *minj,INT *mink,INT *maxi,INT *maxj,INT *maxk,INT *inumb);
extern void bess3_(INT *ib,INT *nx,INT *ny,INT *nz,INT *inumb,INT *ibess,INT *jbess,INT *kbess,INT *ibcode);
extern void getm3_(INT *nx,INT *ny,INT *nz,INT *nvert,INT *nel,REAL *xcoord,REAL *ycoord,REAL *zcoord,INT *je,INT *iflags,INT *ib,INT *inumb);
