#####################################################
# Last Modified 2017-03-08 --ltz
####################################################
# SRC File name
SRCFILE = HDEquation

# if you have compiled hazmath with suitesparse support, uncomment the
# two lines below.
SSDIR = /usr/local
SSLIB = -L$(SSDIR)/lib -lsuitesparseconfig -lcholmod -lamd -lcolamd -lccolamd -lcamd -lspqr -lumfpack -lamd -lcxsparse

LIBS_ADD = $(SSLIB)

sinclude ../examples.mk


