#####################################################
# Navier-Stokes example
####################################################

# SRC File name
SRCFILE = navierstokes
HEADERS = ns_data.h ns_system.h stokes_precond.h

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -g

## If an external libraries support is compiled in the hazmath library,
## uncomment  the corresponding lines below:
WITH_SUITESPARSE=1
WITH_LAPACK=1

sinclude ../examples.mk
