#####################################################
# Last Modified 2019-06-10 --jha
####################################################

# SRC File name
SRCFILE = gmg

HEADERS = gmg_routines.h rhs_bc.h

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -O3

WITH_SUITESPARSE=0 

sinclude ../examples.mk
