#####################################################
# Last Modified 2019-06-10 --jha
####################################################

# SRC File name
SRCFILE = gmg

HEADERS = gmg_routines.h rhs_bc.h

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -O3

## If external libraries support is compiled in the hazmath library,
## uncomment  the corresponding line below:
WITH_SUITESPARSE=1
WITH_LAPACK=1

sinclude ../examples.mk
