
#ifndef BOOL_EG_MECHANICS
#define BOOL_EG_MECHANICS true
#endif

#ifndef BOOL_EG_PRESSURE
#define BOOL_EG_PRESSURE true
#endif

#ifndef BOOL_WEAKLY_IMPOSED_BC
#define BOOL_WEAKLY_IMPOSED_BC true
#endif


#ifndef LAME_LAMBDA_GLOBAL
#define LAME_LAMBDA_GLOBAL 0e+00
#endif

#ifndef PENALTY_PARAMETER_GLOBAL
#define PENALTY_PARAMETER_GLOBAL 1e+00
#endif

#ifndef BC_PENALTY_PARAMETER_GLOBAL
#define BC_PENALTY_PARAMETER_GLOBAL 1e+00
#endif

#ifndef PENALTY_PARAMETER_PRESSURE_GLOBAL
#define PENALTY_PARAMETER_PRESSURE_GLOBAL 0e+00
#endif

#ifndef BC_PENALTY_PARAMETER_PRESSURE_GLOBAL
#define BC_PENALTY_PARAMETER_PRESSURE_GLOBAL 0e+00
#endif

#ifndef THETA_PARAMETER
#define THETA_PARAMETER 0e+00
#endif

#ifndef TOTAL_NUM_CYCLES_GLOBAL
#define TOTAL_NUM_CYCLES_GLOBAL 3
#endif

// the LAME_MU_GLOBAL is not used in the code yet...
#ifndef LAME_MU_GLOBAL
#define LAME_MU_GLOBAL 1.
#endif
