#####################################################
# Last Modified 2019-06-10 --jha
####################################################

# SRC File name
SRCFILE = basic_elliptic

HEADERS = $(SRCFILE)_data.h

INCLUDE =

LIBS =

# Switch between debug or optimized
CFLAGS = -g
FFLAGS = -g


## If an external libraries support is compiled in the hazmath library,
## uncomment  the corresponding lines below:
WITH_SUITESPARSE=1
WITH_LAPACK=1

sinclude ../examples.mk
